menu:
- {name: 'papers', url: '/papers'}
- {name: 'courses', url: '/courses'}
- {name: 'vita', url: '/assets/Ruolong_Xiao_CV.pdf'}
# - {name: 'cv', url: '/cv'}

courses:
- {name: 'Price Theory', url: 'micro-undergrad.md'}
- {name: 'Game Theory', url: 'international-undergrad'}
- {name: 'Political Economy', url: 'international-undergrad'}

social:
- {icon: 'github', link: 'https://ruolongxiao.github.io'}
- {icon: 'twitter', link: 'https://twitter.com/xiaoruolong'}
- {icon: 'mail', link: 'ruolongxiao@gmail.com'}
- {icon: 'linkedin', link: 'https://linkedin.com/Ruolong Xiao'}

#contacts:
#- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
